admin: 'admin@21lou.net'


site:
  name: 'app'
  domain: 'app.com'

nav:
  items: [
    {cname: '设置', controller: 'settings', link: '/cpanel/settings'}, 
    {cname: '用户', controller: 'users', link: '/cpanel/users'},
  ]

fnav:
  items: [
  ]
