admin: 'iamalazyrat@gmail.com'

site:
  name: 'app'
  domain: 'app.com'

nav:
  items: [
    {cname: '设置', controller: 'settings', link: '/cpanel/settings'}, 
    {cname: '分类', controller: 'sections', link: '/cpanel/sections'}, 
  ]

fnav:
  items: [
  ]
