admin: 'iamalazyrat@gmail.com'

site:
  name: 'app'
  domain: 'app.com'

nav:
  items: [
    {cname: '设置', controller: 'settings', link: '/cpanel/settings'}, 
    {cname: '分类', controller: 'sections', link: '/cpanel/sections'}, 
    {cname: '节点', controller: 'nodes', link: '/cpanel/nodes'}, 
    {cname: '图片', controller: 'images', link: '/cpanel/images'}, 
    {cname: '标签', controller: 'tags', link: '/cpanel/tags'}, 
    {cname: '项', controller: 'items', link: '/cpanel/items'}, 
  ]

fnav:
  items: [
  ]
